# Generated by Django 3.0.7 on 2020-06-17 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.TextField(max_length=100)),
                ('Company_Symbol', models.TextField(max_length=50)),
                ('Purchase_Date', models.DateField()),
                ('Purchase_Cost', models.DecimalField(decimal_places=3, max_digits=7)),
                ('Quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
